apiVersion: v1
kind: Pod
metadata:
  name: kafka-client
  namespace: kafka
spec:
  containers:
  - name: kafka
    image: docker.io/bitnami/kafka:2.7.0-debian-10-r35
    command:
      - sh
      - -c
      - "sleep infinity"
  restartPolicy: Never
