server:
  port: 8088

---

spring:
  profiles: default
  cloud:
    gateway:
      routes:
        - id: taxicall
          uri: http://localhost:8081
          predicates:
            - Path=/taxicalls/** 
        - id: taximanage
          uri: http://localhost:8082
          predicates:
            - Path=/taximanages/** 
        - id: taxiassign
          uri: http://localhost:8084
          predicates:
            - Path=/taxiassigns/** 
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins:
              - "*"
            allowedMethods:
              - "*"
            allowedHeaders:
              - "*"
            allowCredentials: true


---

spring:
  profiles: docker
  cloud:
    gateway:
      routes:
        - id: taxicall
          uri: http://taxicall:8080
          predicates:
            - Path=/taxicalls/** 
        - id: taximanage
          uri: http://taximanage:8080
          predicates:
            - Path=/taximanages/** 
        - id: taxiassign
          uri: http://taxiassign:8080
          predicates:
            - Path=/taxiassigns/** 
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins:
              - "*"
            allowedMethods:
              - "*"
            allowedHeaders:
              - "*"
            allowCredentials: true

server:
  port: 8080
