apiVersion: apps/v1
kind: Deployment
metadata:
  name: taximanage
  labels:
    app: taximanage
spec:
  replicas: 1
  selector:
    matchLabels:
      app: taximanage
  template:
    metadata:
      labels:
        app: taximanage
    spec:
      containers:
        - name: command-handler
          image: username/taximanage-command-handler:latest
          ports:
            - containerPort: 8082
        - name: policy-handler
          image: username/taximanage-policy-handler:latest
